# Generated by Django 5.0.4 on 2024-07-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Fund'), ('W', 'Withdrawal'), ('T', 'Transfer')], max_length=1),
        ),
    ]
